### ISSUE TITLE
请教下怎么使用

### ISSUE THREAD

**Issue by pannifeng** [Jxpro/custom-rustdesk#1]
加密之后怎么使用呢，用的是win10免安装版，会在C:\Users\pannifeng\AppData\Roaming\RustDesk\config和
C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config都生成配置文件RustDesk.toml，直接把加密之后的id替换配置文件中的enc_id没效果，RustDesk.toml里面还有个sale和key_pair字段

**Comment by Jxpro** [comment]
bug已修复，请先使用验证程序确认uuid正确，然后再重新生成enc_id。如有其他问题请再附上截图，有用希望可以给个star
