### ISSUE TITLE
爱了，属于是想打瞌睡刚好递了枕头

### ISSUE THREAD

**Issue by orzchen** [Jxpro/custom-rustdesk#2]
感谢作者大大，今天刚碰到rustdesk加密了id，没想到找到这个项目还是今天更新了热乎的。

有一个小小的问题想请教一下，由于本人不懂rust，看了rustdesk的源码也看不懂。以前版本的rustdesk的配置文件中是保存了明文id和password明文，现在password好像是不保存在文件中了，配置文件中是空的，所以想请问一下您现在rustdesk的password是如何存储的，现在貌似是每次启动都是随机密码了，是不是不会落地存储了（默认配置情况下）。

**Comment by Jxpro** [comment]
id可以根据该项目自定义，将生成的enc_id替换到配置文件中。
password可以在设置里面选择固定或随机。
